<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>ModAssets</RootNamespace>
        <LangVersion>latest</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <Import Project="../Build.props" />

    <ItemGroup>
      <Content Include="..\Build.props">
        <Link>Build.props</Link>
      </Content>
    </ItemGroup>

    <Target Name="CopyFiles" AfterTargets="Build">
        <ItemGroup>
            <Content Include="$(ProjectDir)Content\**\*.*" />
        </ItemGroup>
        <Copy SourceFiles="@(Content)" DestinationFolder="$(ModDeployDir)%(RecursiveDir)" />
    </Target>


</Project>
